site_name: NVIDIA Jetson Generative AI Lab
site_url: 
site_description: Showcasing generative AI projects that run on Jetson
copyright: Copyright &copy; 2023 NVIDIA Corporation
## Repository
#repo_name: jetson-generative-ai-playground
#repo_url: https://github.com/NVIDIA-AI-IOT/jetson-generative-ai-playground
edit_uri: ''
theme:
  name: "material"
  custom_dir: docs/overrides
  favicon: images/favicon_navy.png
  logo: images/cube_white.png
  font: Incosolata
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: nv-black-green

  features:
      - navigation.indexes
      - navigation.expand
      - navigation.tabs
      - navigation.tabs.sticky
      # - navigation.sections
      - navigation.top
      - content.tabs.link
      - content.code.copy
      
plugins:
  - search
  - redirects:
      redirect_maps:
        'tutorial_efficientvit.md': 'vit/tutorial_efficientvit.md'
        'tutorial_nanosam.md': 'vit/tutorial_nanosam.md'
        'tutorial_nanoowl.md': 'vit/tutorial_nanoowl.md'
        'tutorial_sam.md': 'vit/tutorial_sam.md'
        'tutorial_tam.md': 'vit/tutorial_tam.md'
  
use_directory_urls: false

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - meta
  - footnotes

extra_css:
  - css/colors.css
  - css/extra.css

nav:
  - Home: index.md
  - Tutorials:
    - Introduction: tutorial-intro.md
    - Text (LLM):
      - text-generation-webui: tutorial_text-generation.md 
      - llamaspeak 🆕: tutorial_llamaspeak.md
    - Text + Vision (VLM):
      - Mini-GPT4: tutorial_minigpt4.md
      - LLaVA: tutorial_llava.md
      # - NeVA: tutorial_NeVA.md
    - Image Generation:
      - Stable Diffusion: tutorial_stable-diffusion.md
      - Stable Diffusion XL: tutorial_stable-diffusion-xl.md
    - Vision Transformers (ViT): 
      - vit/index.md
      - EfficientViT 🆕: vit/tutorial_efficientvit.md
      - NanoSAM: vit/tutorial_nanosam.md
      - NanoOWL 🆕: vit/tutorial_nanoowl.md
      - SAM: vit/tutorial_sam.md
      - TAM: vit/tutorial_tam.md
    # - NanoOWL: tutorial_nanoowl.md
    - Vector Database:
      - NanoDB: tutorial_nanodb.md
    - Audio:
      - AudioCraft 🆕: tutorial_audiocraft.md
      - Whisper 🆕: tutorial_whisper.md
    # - Tools:
    #   - LangChain: tutorial_distillation.md
    - Tips:
      - 📑 Knowledge Distillation: tutorial_distillation.md
      - 🔖 SSD + Docker: tips_ssd-docker.md
      - 🔖 Memory optimization: tips_ram-optimization.md
  - Benchmarks: benchmarks.md
  - Community Articles: community_articles.md
  - Try: try.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-SXH8S4Y8RW
  
