site_name: Jetson Generative AI Playground
site_url: 
site_description: Showcasing generative AI projects that run on Jetson
## Repository
repo_name: jetson-generative-ai-playground
repo_url: https://github.com/NVIDIA-AI-IOT/jetson-generative-ai-playground
edit_uri: ''
theme:
  name: "material"
  custom_dir: docs/overrides
  favicon: images/favicon_navy.png
  logo: images/cube_white.png
  font: Incosolata
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: playful-purple

  features:
      # - navigation.indexes
      - navigation.expand
      - navigation.tabs
      - navigation.tabs.sticky
      # - navigation.sections
      - navigation.top
      - content.tabs.link
      - content.code.copy

plugins:
  - search

  
use_directory_urls: false

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - meta
  - footnotes

extra_css:
  - css/colors.css
  - css/extra.css

nav:
  - Home: index.md
  - Tutorials:
    - About Jetson: tutorial-intro.md
    - Text:
      - text-generation-webui: tutorial_text-generation.md 
    # - LLM + ASR/TTS:
    #   - LlamaSpeak: tutorial_llamaspeak.md
    - Text + Vision:
      - Mini-GPT4: tutorial_minigpt4.md
      - LLaVA: tutorial_llava.md
      # - NeVA: tutorial_NeVA.md
    - Image Generation:
      - Stable Diffusion: tutorial_stable-diffusion.md
    - Vision Transformers (ViT):
      - SAM: tutorial_sam.md
      - NanoSAM: tutorial_nanosam.md
      - NanoOWL: tutorial_nanoowl.md
      - TAM: tutorial_tam.md
    # - NanoOWL: tutorial_nanoowl.md
    - Vector Database:
      - NanoDB: tutorial_nanodb.md
    # - Tools:
    #   - LangChain: tutorial_distillation.md
    - Tips:
      - 📑 Knowledge Distillation: tutorial_distillation.md
      - 🔖 SSD + Docker: tips_ssd-docker.md
      - 🔖 Memory optimization: tips_ram-optimization.md
  - Benchmarks: benchmarks.md
  - Community Articles: community_articles.md
  - Buy: buy.md

extra:
  analytics:
    provider: google
    property: G-SXH8S4Y8RW
  