site_name: Jetson Generative AI Playground
theme:
    name: "material"
    custom_dir: docs/theme_override_home/
    favicon: images/m48-document-support-guide-256px-wht.png
    logo: images/m48-document-support-guide-256px-wht.png
    font: Incosolata
    features:
       - navigation.indexes
       - navigation.expand
       - navigation.tabs
       - content.tabs.link

repo_url: https://gitlab-master.nvidia.com/Jetson-TME/jetson-generative-ai-playground

plugins:
  - search
use_directory_urls: false

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - meta

extra_css:
  - css/colors.css
  - css/extra.css

nav:

  - Home: index.md
  - Getting started: getting-started.md
  - Tutorials: tutorials.md
  - Buy: buy.md

extra:
  analytics:
    provider: google
    property: 
  