site_name: Jetson Generative AI Playground
site_url: 
site_description: Showcasing generative AI projects that run on Jetson
## Repository
repo_name: jetson-generative-ai-playground
repo_url: https://github.com/NVIDIA-AI-IOT/jetson-generative-ai-playground
edit_uri: ''
theme:
  name: "material"
  custom_dir: docs/overrides
  favicon: images/favicon_navy.png
  logo: images/cube_white.png
  font: Incosolata
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: playful-purple

  features:
      - navigation.indexes
      - navigation.expand
      - navigation.tabs
      - navigation.tabs.sticky
      - content.tabs.link
      - content.code.copy

plugins:
  - search

  
use_directory_urls: false

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - meta

extra_css:
  - css/colors.css
  - css/extra.css

nav:
  - Home: index.md
  - Tutorials:
    - Intro: tutorial-intro.md
    - 1. Text Generation: tutorial_text-generation.md 
    - 2. Image Generation: tutorial_diffusion.md
    - 3. Distillation: tutorial_distillation.md
  - Try: try.md

extra:
  analytics:
    provider: google
    property: G-SXH8S4Y8RW
  